### ISSUE TITLE
Service failing to start - any ideas?

### ISSUE THREAD

**Issue by Webreaper** [Misioslav/expressvpn#34]
I restarted some containers over the weekend, and since then ExpressVPN hasn't started properly or connected. All I get is this:

<img width="515" alt="Screenshot 2024-02-05 at 08 08 33" src="https://github.com/Misioslav/expressvpn/assets/4901102/b64822fd-47db-4953-a296-4aef6140a91b">

I'm using latest - I see you made some changes to auto-update expressvpn. However, I also see the same with 3.60.0.4. I'm running the fix to create tun file structure.

Any ideas, or any hints on how to debug?

**Comment by Misioslav** [comment]
`AUTO_UPDATE` will work only when the env is set up for it, otherwise, it won't work.

It seems the service cannot be restarted and it goes into the loop to try to do it upon the next container restart.
I've done it that way as I've noticed that on occasion this cation can fail and usually after a restart or two it works again but if it doesn't and its an endless loop there might be some issues between the images because of the recent changes. Can you remove the image from your local machine and pull it again, then recreate it?

**Comment by Webreaper** [comment]
I've tried completely cleaning it (i.e., `docker rm expressvpn` and then re-pulling and recreating it. I get the same every time. :(

**Comment by Misioslav** [comment]
> I've tried completely cleaning it (i.e., `docker rm expressvpn` and then re-pulling and recreating it. I get the same every time. :(

I understand that nothing changed in the configuration and the only change is my last change to add `auto_update`?

**Comment by Webreaper** [comment]
Yeah, it's weird. Even if I go back to 3.60.4 I'm seeing the same thing. I have no idea why it's broken!!

**Comment by Webreaper** [comment]
Okay, weird. Docker-composed DOWN all of my services. Deleted everything. Re-pulled, docker compose up, and now it's working. I literally have no idea. 

Sorry for the noise!
