### ISSUE TITLE
Trying to understand how the heathchecks.io integration works

### ISSUE THREAD

**Issue by martinbaines** [Misioslav/expressvpn#40]
I've read the documentation but I cannot work out how the healthchecks.io integration works.

I have tried both:
`HEALTHCHECK=<ID>`
and
`HEALTHCHECK=https://hc-ping.com/<ID>
`
In both cases the container seems to start and show healthy, but in neither  do I see any pings on my healthchecks.io status page

TIA

**Comment by Misioslav** [comment]
Hey Martin,

For me the setting looks like

![Zrzut ekranu 2024-05-17 o 12 10 36](https://github.com/Misioslav/expressvpn/assets/46351329/baf7c277-7d04-4ec2-8735-710e7764dcbf)

and for the ID

![Zrzut ekranu 2024-05-17 o 12 11 18](https://github.com/Misioslav/expressvpn/assets/46351329/42fb2149-8d0e-489e-bb17-72c0a3f9f720)

so in short its UUID Slug that you need.

**Comment by martinbaines** [comment]
Hi.

Okay, I spent a bit of time looking at the code, and I think I can see the
issue. This only works if the DDNS environment variable is set.

There seems to be an assumption in the healthcheck.sh code that a variable
called IP will be set up, but I do not think it is unless it is passed in
(which I did not). The result of that is the logic means the checkIP
variable in the script gets set to null. That means that script just falls
through to an "exit 0" without executing a curl to healthchecks.io

I added a DDNS environment variable in the docker-compose.yml and it now
works: i.e, the container is marked healthy, and the curl informs
healthcheck.io the container is healthy.

Hope this helps
Cheers
Martin

*e: ***@***.*** ***@***.***>*
*t: +44 7812 980635 (UK)*
*t: +34 950 950 036 (SPAIN)*

**Comment by Misioslav** [comment]
You have to pass DDNS or IP env variable in order to get it work. The assumption is that health check checks if the IP of the host is different than the one in the container (when its connected) and in order to do so IP is needed (in any of the forms) so it can be compered. Otherwise healtcheck won't work because Im not interested in knowing if container works but if it works correctly (so if VPN is up and running which it not equal to the container working). If none of those env variables is passed it will not trigger the request.
